# Generated by Django 3.2 on 2021-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='uploads/images/', verbose_name='用户头像')),
                ('introduce', models.FileField(upload_to='uploads/introduce/', verbose_name='个人简历')),
            ],
        ),
    ]
